version: '3.8'

services:
  chess-engines:
    build: .
    container_name: chess-engines-builder
    volumes:
      - ./implementations:/workspace/implementations
      - ./build_results:/workspace/build_results
    working_dir: /workspace
    command: ["./build_all.sh"]
    environment:
      - DEBIAN_FRONTEND=noninteractive
    
  # Individual language services for testing
  crystal-chess:
    build: ./implementations/crystal
    container_name: crystal-chess
    volumes:
      - ./implementations/crystal:/app
    
  go-chess:
    build: ./implementations/go  
    container_name: go-chess
    volumes:
      - ./implementations/go:/app
      
  rust-chess:
    build: ./implementations/rust
    container_name: rust-chess
    volumes:
      - ./implementations/rust:/usr/src/chess
      
  python-chess:
    build: ./implementations/python
    container_name: python-chess
    volumes:
      - ./implementations/python:/app
      
  typescript-chess:
    build: ./implementations/typescript
    container_name: typescript-chess
    volumes:
      - ./implementations/typescript:/app