// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Evaluation from "./Evaluation.js";
import * as MoveGenerator from "./MoveGenerator.js";

function minimax(state, depth, alpha, beta) {
  if (depth === 0) {
    return Evaluation.evaluateGameState(state);
  }
  var moves = MoveGenerator.generateLegalMoves(state);
  var moveCount = moves.length;
  if (moveCount === 0) {
    if (MoveGenerator.isKingInCheck(state, state.turn)) {
      if (state.turn === "White") {
        return -100000;
      } else {
        return 100000;
      }
    } else {
      return 0;
    }
  }
  if (state.turn === "White") {
    var maxEval = -1000000;
    var alphaRef = alpha;
    var index = 0;
    while(index < moveCount && beta > alphaRef) {
      var move = Belt_Array.getExn(moves, index);
      var nextState = MoveGenerator.makeMove(state, move);
      var evaluation = minimax(nextState, depth - 1 | 0, alphaRef, beta);
      if (evaluation > maxEval) {
        maxEval = evaluation;
      }
      if (evaluation > alphaRef) {
        alphaRef = evaluation;
      }
      index = index + 1 | 0;
    };
    return maxEval;
  }
  var minEval = 1000000;
  var betaRef = beta;
  var index$1 = 0;
  while(index$1 < moveCount && betaRef > alpha) {
    var move$1 = Belt_Array.getExn(moves, index$1);
    var nextState$1 = MoveGenerator.makeMove(state, move$1);
    var evaluation$1 = minimax(nextState$1, depth - 1 | 0, alpha, betaRef);
    if (evaluation$1 < minEval) {
      minEval = evaluation$1;
    }
    if (evaluation$1 < betaRef) {
      betaRef = evaluation$1;
    }
    index$1 = index$1 + 1 | 0;
  };
  return minEval;
}

function findBestMove(state, depth) {
  var moves = MoveGenerator.generateLegalMoves(state);
  var moveCount = moves.length;
  if (moveCount === 0) {
    return ;
  }
  var bestMove = Belt_Array.getExn(moves, 0);
  var bestEval = state.turn === "White" ? ({
        contents: -1000000
      }) : ({
        contents: 1000000
      });
  for(var index = 0; index < moveCount; ++index){
    var move = Belt_Array.getExn(moves, index);
    var nextState = MoveGenerator.makeMove(state, move);
    var evaluation = minimax(nextState, depth - 1 | 0, -1000000, 1000000);
    if (state.turn === "White") {
      if (evaluation > bestEval.contents) {
        bestEval.contents = evaluation;
        bestMove = move;
      }
      
    } else if (evaluation < bestEval.contents) {
      bestEval.contents = evaluation;
      bestMove = move;
    }
    
  }
  return [
          bestMove,
          bestEval.contents
        ];
}

export {
  minimax ,
  findBestMove ,
}
/* MoveGenerator Not a pure module */
