// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function isDrawByRepetition(state) {
  var currentHash = state.zobristHash;
  var count = 1;
  var historyLen = state.positionHistory.length;
  var startIdx = historyLen > state.halfmoveClock ? historyLen - state.halfmoveClock | 0 : 0;
  var found = false;
  var i = historyLen - 1 | 0;
  while(i >= startIdx && !found) {
    if (Belt_Array.getExn(state.positionHistory, i) === currentHash) {
      count = count + 1 | 0;
      if (count >= 3) {
        found = true;
      }
      
    }
    i = i - 1 | 0;
  };
  return found;
}

function isDrawByFiftyMoves(state) {
  return state.halfmoveClock >= 100;
}

function isDraw(state) {
  if (isDrawByRepetition(state)) {
    return true;
  } else {
    return state.halfmoveClock >= 100;
  }
}

export {
  isDrawByRepetition ,
  isDrawByFiftyMoves ,
  isDraw ,
}
/* No side effect */
