// Generated by ReScript, PLEASE EDIT WITH CARE


var files = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h"
];

var ranks = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8"
];

var promotionPieces = [
  "Queen",
  "Rook",
  "Bishop",
  "Knight"
];

function pieceValue(pieceType) {
  switch (pieceType) {
    case "Pawn" :
        return 100;
    case "Knight" :
        return 320;
    case "Bishop" :
        return 330;
    case "Rook" :
        return 500;
    case "Queen" :
        return 900;
    case "King" :
        return 20000;
    
  }
}

export {
  files ,
  ranks ,
  promotionPieces ,
  pieceValue ,
}
/* No side effect */
