# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# Development and testing
group :development, :test do
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-performance', '~> 1.18'
  gem 'rspec', '~> 3.12'
end