// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.js";
import * as Zobrist from "./Zobrist.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function createEmptyBoard() {
  return Caml_array.make(64, undefined);
}

function createInitialBoard() {
  var board = Caml_array.make(64, undefined);
  var setPieceAt = function (square, pieceType, color) {
    Belt_Array.setExn(board, square, {
          pieceType: pieceType,
          color: color
        });
  };
  setPieceAt(0, "Rook", "White");
  setPieceAt(1, "Knight", "White");
  setPieceAt(2, "Bishop", "White");
  setPieceAt(3, "Queen", "White");
  setPieceAt(4, "King", "White");
  setPieceAt(5, "Bishop", "White");
  setPieceAt(6, "Knight", "White");
  setPieceAt(7, "Rook", "White");
  for(var i = 8; i <= 15; ++i){
    setPieceAt(i, "Pawn", "White");
  }
  setPieceAt(56, "Rook", "Black");
  setPieceAt(57, "Knight", "Black");
  setPieceAt(58, "Bishop", "Black");
  setPieceAt(59, "Queen", "Black");
  setPieceAt(60, "King", "Black");
  setPieceAt(61, "Bishop", "Black");
  setPieceAt(62, "Knight", "Black");
  setPieceAt(63, "Rook", "Black");
  for(var i$1 = 48; i$1 <= 55; ++i$1){
    setPieceAt(i$1, "Pawn", "Black");
  }
  return board;
}

function createInitialState() {
  var state_board = createInitialBoard();
  var state_castlingRights = {
    whiteKingside: true,
    whiteQueenside: true,
    blackKingside: true,
    blackQueenside: true
  };
  var state_moveHistory = [];
  var state_positionHistory = [];
  var state_irreversibleHistory = [];
  var state = {
    board: state_board,
    turn: "White",
    castlingRights: state_castlingRights,
    enPassantTarget: undefined,
    halfmoveClock: 0,
    fullmoveNumber: 1,
    moveHistory: state_moveHistory,
    zobristHash: 0n,
    positionHistory: state_positionHistory,
    irreversibleHistory: state_irreversibleHistory
  };
  return {
          board: state_board,
          turn: "White",
          castlingRights: {
            whiteKingside: true,
            whiteQueenside: true,
            blackKingside: true,
            blackQueenside: true
          },
          enPassantTarget: undefined,
          halfmoveClock: 0,
          fullmoveNumber: 1,
          moveHistory: state_moveHistory,
          zobristHash: Zobrist.computeHash(state),
          positionHistory: state_positionHistory,
          irreversibleHistory: state_irreversibleHistory
        };
}

function getPiece(state, square) {
  if (square < 0 || square >= 64) {
    return ;
  } else {
    return Belt_Array.getExn(state.board, square);
  }
}

function setPiece(state, square, piece) {
  var newBoard = state.board.slice(0);
  Belt_Array.setExn(newBoard, square, piece);
  return {
          board: newBoard,
          turn: state.turn,
          castlingRights: state.castlingRights,
          enPassantTarget: state.enPassantTarget,
          halfmoveClock: state.halfmoveClock,
          fullmoveNumber: state.fullmoveNumber,
          moveHistory: state.moveHistory,
          zobristHash: state.zobristHash,
          positionHistory: state.positionHistory,
          irreversibleHistory: state.irreversibleHistory
        };
}

function boardToString(state) {
  var output = "  a b c d e f g h\n";
  for(var rowIndex = 0; rowIndex <= 7; ++rowIndex){
    var rank = 7 - rowIndex | 0;
    output = output + String(rank + 1 | 0) + " ";
    for(var file = 0; file <= 7; ++file){
      var square = (rank << 3) + file | 0;
      var piece = getPiece(state, square);
      var $$char = piece !== undefined ? Utils.pieceToChar(piece) : ".";
      output = output + $$char + " ";
    }
    output = output + String(rank + 1 | 0) + "\n";
  }
  output = output + "  a b c d e f g h\n\n";
  var turnLabel = state.turn === "White" ? "White" : "Black";
  output = output + turnLabel + " to move";
  return output;
}

function parseFen(fen) {
  var parts = Js_string.split(" ", fen.trim());
  if (parts.length < 4) {
    return {
            TAG: "Error",
            _0: "Invalid FEN string"
          };
  }
  var pieces = Belt_Array.getExn(parts, 0);
  var turnPart = Belt_Array.getExn(parts, 1);
  var castlingPart = Belt_Array.getExn(parts, 2);
  var enPassantPart = Belt_Array.getExn(parts, 3);
  var value = Belt_Array.get(parts, 4);
  var halfmovePart = value !== undefined ? value : "0";
  var value$1 = Belt_Array.get(parts, 5);
  var fullmovePart = value$1 !== undefined ? value$1 : "1";
  var board = Caml_array.make(64, undefined);
  var square = 56;
  var length = pieces.length;
  for(var i = 0; i < length; ++i){
    var $$char = Js_string.charAt(i, pieces);
    var exit = 0;
    switch ($$char) {
      case "/" :
          square = square - 16 | 0;
          break;
      case "1" :
      case "2" :
      case "3" :
      case "4" :
      case "5" :
      case "6" :
      case "7" :
      case "8" :
          exit = 1;
          break;
      default:
        var piece = Utils.charToPiece($$char);
        if (piece !== undefined) {
          Belt_Array.setExn(board, square, piece);
          square = square + 1 | 0;
        }
        
    }
    if (exit === 1) {
      var step = Belt_Int.fromString($$char);
      if (step !== undefined) {
        square = square + step | 0;
      }
      
    }
    
  }
  var turn = turnPart === "w" ? "White" : "Black";
  var hasCastling = function ($$char) {
    return Js_string.indexOf(castlingPart, $$char) !== -1;
  };
  var castlingRights_whiteKingside = hasCastling("K");
  var castlingRights_whiteQueenside = hasCastling("Q");
  var castlingRights_blackKingside = hasCastling("k");
  var castlingRights_blackQueenside = hasCastling("q");
  var castlingRights = {
    whiteKingside: castlingRights_whiteKingside,
    whiteQueenside: castlingRights_whiteQueenside,
    blackKingside: castlingRights_blackKingside,
    blackQueenside: castlingRights_blackQueenside
  };
  var enPassantTarget = enPassantPart === "-" ? undefined : Utils.parseSquare(enPassantPart);
  var value$2 = Belt_Int.fromString(halfmovePart);
  var halfmoveClock = value$2 !== undefined ? value$2 : 0;
  var value$3 = Belt_Int.fromString(fullmovePart);
  var fullmoveNumber = value$3 !== undefined ? value$3 : 1;
  var state_moveHistory = [];
  var state_positionHistory = [];
  var state_irreversibleHistory = [];
  var state = {
    board: board,
    turn: turn,
    castlingRights: castlingRights,
    enPassantTarget: enPassantTarget,
    halfmoveClock: halfmoveClock,
    fullmoveNumber: fullmoveNumber,
    moveHistory: state_moveHistory,
    zobristHash: 0n,
    positionHistory: state_positionHistory,
    irreversibleHistory: state_irreversibleHistory
  };
  return {
          TAG: "Ok",
          _0: {
            board: board,
            turn: turn,
            castlingRights: castlingRights,
            enPassantTarget: enPassantTarget,
            halfmoveClock: halfmoveClock,
            fullmoveNumber: fullmoveNumber,
            moveHistory: state_moveHistory,
            zobristHash: Zobrist.computeHash(state),
            positionHistory: state_positionHistory,
            irreversibleHistory: state_irreversibleHistory
          }
        };
}

function exportFen(state) {
  var pieces = "";
  for(var rowIndex = 0; rowIndex <= 7; ++rowIndex){
    var rank = 7 - rowIndex | 0;
    var emptyCount = 0;
    for(var file = 0; file <= 7; ++file){
      var square = (rank << 3) + file | 0;
      var piece = getPiece(state, square);
      if (piece !== undefined) {
        if (emptyCount > 0) {
          pieces = pieces + String(emptyCount);
          emptyCount = 0;
        }
        pieces = pieces + Utils.pieceToChar(piece);
      } else {
        emptyCount = emptyCount + 1 | 0;
      }
    }
    if (emptyCount > 0) {
      pieces = pieces + String(emptyCount);
    }
    if (rank > 0) {
      pieces = pieces + "/";
    }
    
  }
  var turn = state.turn === "White" ? "w" : "b";
  var castling = "";
  if (state.castlingRights.whiteKingside) {
    castling = castling + "K";
  }
  if (state.castlingRights.whiteQueenside) {
    castling = castling + "Q";
  }
  if (state.castlingRights.blackKingside) {
    castling = castling + "k";
  }
  if (state.castlingRights.blackQueenside) {
    castling = castling + "q";
  }
  var castlingStr = castling === "" ? "-" : castling;
  var square$1 = state.enPassantTarget;
  var enPassant = square$1 !== undefined ? Utils.squareToString(square$1) : "-";
  return pieces + " " + turn + " " + castlingStr + " " + enPassant + " " + String(state.halfmoveClock) + " " + String(state.fullmoveNumber);
}

export {
  createEmptyBoard ,
  createInitialBoard ,
  createInitialState ,
  getPiece ,
  setPiece ,
  boardToString ,
  parseFen ,
  exportFen ,
}
/* Zobrist Not a pure module */
