// Generated by ReScript, PLEASE EDIT WITH CARE


var Stream = {};

var Process = {};

var Interface = {};

var Readline = {
  Interface: Interface
};

export {
  Stream ,
  Process ,
  Readline ,
}
/* No side effect */
