// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as MoveGenerator from "./MoveGenerator.js";

function perft(state, depth) {
  if (depth === 0) {
    return 1;
  }
  var moves = MoveGenerator.generateLegalMoves(state);
  var nodes = 0;
  var moveCount = moves.length;
  for(var index = 0; index < moveCount; ++index){
    var move = Belt_Array.getExn(moves, index);
    var nextState = MoveGenerator.makeMove(state, move);
    nodes = nodes + perft(nextState, depth - 1 | 0) | 0;
  }
  return nodes;
}

export {
  perft ,
}
/* MoveGenerator Not a pure module */
