// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function oppositeColor(color) {
  if (color === "White") {
    return "Black";
  } else {
    return "White";
  }
}

function modInt(value, modulus) {
  return value - Math.imul(Caml_int32.div(value, modulus), modulus) | 0;
}

function absInt(value) {
  if (value < 0) {
    return -value | 0;
  } else {
    return value;
  }
}

function parseSquare(squareStr) {
  if (squareStr.length !== 2) {
    return ;
  }
  var fileChar = Js_string.charAt(0, squareStr);
  var rankChar = Js_string.charAt(1, squareStr);
  var match = Belt_Array.getIndexBy(Types.files, (function (f) {
          return f === fileChar;
        }));
  var match$1 = Belt_Array.getIndexBy(Types.ranks, (function (r) {
          return r === rankChar;
        }));
  if (match !== undefined && match$1 !== undefined) {
    return (match$1 << 3) + match | 0;
  }
  
}

function squareToString(square) {
  var fileIndex = modInt(square, 8);
  var rankIndex = square / 8 | 0;
  var match = Belt_Array.get(Types.files, fileIndex);
  var match$1 = Belt_Array.get(Types.ranks, rankIndex);
  if (match !== undefined && match$1 !== undefined) {
    return match + match$1;
  } else {
    return "??";
  }
}

function pieceTypeToChar(pieceType) {
  switch (pieceType) {
    case "Pawn" :
        return "P";
    case "Knight" :
        return "N";
    case "Bishop" :
        return "B";
    case "Rook" :
        return "R";
    case "Queen" :
        return "Q";
    case "King" :
        return "K";
    
  }
}

function pieceToChar(piece) {
  var base = pieceTypeToChar(piece.pieceType);
  var match = piece.color;
  if (match === "White") {
    return base;
  } else {
    return base.toLowerCase();
  }
}

function charToPiece($$char) {
  if ($$char === "") {
    return ;
  }
  var upper = $$char.toUpperCase();
  var isWhite = $$char === upper;
  var color = isWhite ? "White" : "Black";
  switch (upper) {
    case "B" :
        return {
                pieceType: "Bishop",
                color: color
              };
    case "K" :
        return {
                pieceType: "King",
                color: color
              };
    case "N" :
        return {
                pieceType: "Knight",
                color: color
              };
    case "P" :
        return {
                pieceType: "Pawn",
                color: color
              };
    case "Q" :
        return {
                pieceType: "Queen",
                color: color
              };
    case "R" :
        return {
                pieceType: "Rook",
                color: color
              };
    default:
      return ;
  }
}

export {
  oppositeColor ,
  modInt ,
  absInt ,
  parseSquare ,
  squareToString ,
  pieceTypeToChar ,
  pieceToChar ,
  charToPiece ,
}
/* No side effect */
